export const types = {
    AUTHENTICATE:       "AUTHENTICATE",
    AUTHENTICATE_ASYNC: "AUTHENTICATE_ASYNC",
    SIGNUP_ASYNC:       "SIGNUP_ASYNC",
    LOGIN:              "LOGIN",
    INITIALIZE:         "INITIALIZE",
    INITIALIZE_ASYNC:   "INITIALIZE_ASYNC",
};
