export const types = {
    //Sync
    INITIALIZE:   "INITIALIZE",
    AUTHENTICATE: "AUTHENTICATE",

    //Async
    SIGNUP_ASYNC:       "SIGNUP_ASYNC",
    LOGIN_ASYNC:        "LOGIN_ASYNC",
    INITIALIZE_ASYNC:   "INITIALIZE_ASYNC",
    AUTHENTICATE_ASYNC: "AUTHENTICATE_ASYNC",
};
